version: '3.8'

services:
  router-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pancakeswap-router-service
    ports:
      - "3010:3010"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  position-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pancakeswap-position-service
    command: node pancake-position-service.js
    ports:
      - "3110:3110"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3110/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s